### PR TITLE
Update LanguageMiddleware.php

### PR DESCRIPTION
**Pull request by danielebanfi83**
I made a few changes to `__invoke` method for support multi-language not only on index.php or on the page defined as root

### CODE REVIEW

**Comment by dasilvaluis** [comment]
Hello Daniele

Thank you for contributing to my project. However, I truly don't understand what you are trying to do here.
As I can see, you are just removing the initial "/" from the request in the beggining, and adding it later when you return it. The only thing different will be to check the index 0 of the $pathChunks array instead of 1. Moreover, I tested your solution and it doesn't even work properly.
I tested with the example present in the repository and these are the results:

/ -> Shows default language
/pt -> error
/pt/ -> shows de English language
/en -> error
/en/ -> English


But it was cool that you noticed the useless `use MultilingualSlim\Language` in line 5.

**Comment by danielebanfi83** [comment]
Hello Luis,

first, excuse me because I didn't tell you my implementation.

On my app I use twig Templates to render the pages and I make 2 front controllers, `index.php` (the default one) and `dev.php`. Both pages make the same thing, except dev.php that doesn't use cache twig.

If I run your code under dev.php, for example `http://mydomain/dev.php/en/` I always obtain a page not found error, but with my code all is working.

However, I've seen that writing the URI without the final `/`, with my implementation there is always an error. Maybe we just fix this

Your implementation I think is the best on the net running on slim 3 to manage multi-language and I really need that all is working perfectly

Thanks,
Bye

**Comment by dasilvaluis** [comment]
So, as I understand it, you wrote this modification just for development purposes? I believe you could just write index.php in a way which you would have some kind of boolean value stating if you are in a dev or prod environment. You doul even use phpdontenv for that. As far as I can see, you are trying to use this project in a way that doesn't make sense production wise. Am I correct?

Anyway, I don't mean to tell you how you should work, just sharing my view. If you are to make changes on this project in a way that it won't affect in any way it's main functionality, maybe I could merge this pull request. Even then, I beleive that being able to do http://domain.com/some-page/[language] it's an idea that can bring more problems than solutions.

In the meantime, if you push a commit without all the changes except the one on line 5 where you removed the unused code, I will merge it.

Best regards

**Comment by danielebanfi83** [comment]
I did'nt know phpdontenv before, and I thank you for that, but I understand that is something different from what I want.

I agree with you that it's only for development purposes (in my implementation), but I already make my implementation inside a production app, and all is working.

I think that we just have to fix `/en` route, and I think it's only one more `if` statement inside the `__invoke` method.

However, if you prefer your original implementation, ther's no problem, I make only that change on line 5 and I will create one other repository inspired by your work, writing it inside the README file as you already made

**Comment by dasilvaluis** [comment]
Hello 

All you would have to do for me to consider merging this requests is making sure that all the routes are working well on root, be it /, /pt, /pt/, /en, etc, and properly recognize the language on the URL, which is something that is not working at all. For now I do prefer the original implementation obviously, I don't want to break the code :)

Best regards

**Comment by dasilvaluis** [comment]
Since there was no progress, I'm closing this pull-request.

**Pull request closed without merging**
